version: '3'
services:
  next-app:
    image: ghcr.io/itsmesafak/site:recent
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=inan.dev
      - LETSENCRYPT_HOST=inan.dev
      - VIRTUAL_PORT=3000
    container_name: site

networks:
  default:
    external:
      name: nginx-proxy
