version: '3'
services:
    next-app:
        image: ghcr.io/itsmesafak/site:latest
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=inan.dev,www.inan.dev
            - LETSENCRYPT_HOST=inan.dev,www.inan.dev
            - VIRTUAL_PORT=3000
        container_name: site
        volumes: 
            - site_data:/public/data
          
volumes:
    site_data:

networks:
    default:
        external:
            name: nginx-proxy
