name: Deployment to VPS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}

    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/itsmesafak/site:latest

    - name: Copy docker compose prod yaml to target
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: 22
        key: ${{ secrets.SSH }}
        source: "docker-compose.yaml,docker-compose.prod.yaml"
        target: "${{ secrets.HOST_PATH }}"
        
    - name: Composing containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: 22
        key: ${{ secrets.SSH }}
        script: |
           export CR_PAT=${{ secrets.GIT_TOKEN }}
           echo $CR_PAT | docker login ghcr.io -u ItsMeSafak --password-stdin
           cd ${{ secrets.HOST_PATH }}
           docker-compose -f docker-compose.prod.yaml down
           docker-compose -f docker-compose.prod.yaml up -d
          
